#!/bin/sh

[ -z $1 ] && sed -re "s/([.0-9]+) .*/\1/g" /proc/loadavg && exit 0

mpstat $1 1 | grep all | grep -v -i average | sed -re "s/ +/ /g" | sed -re "s/.*all( [.0-9]+){$(($2-1))} ([.0-9]+).*/\2/g"